flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        if form.link.data:
            post.link = form.link.data
        db.session.add(post)
        db.session.commit()
        flash('הפוסט שלך נוצר!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='פוסט חדש', form=form, legend='יצירת פוסט')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if form.link.data:
            post.link = form.link.data
        db.session.commit()
        flash('הפוסט שלך עודכן!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.link.data = post.link
    return render_template('create_post.html', title='עדכון פוסט', form=form, legend='עדכון פוסט')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('הפוסט שלך נמחק!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(
            f'חשבון נוצר בעבור {form.username.data}', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='הרשמה', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('סיסמה או מייל לא נכונים, נסו שוב.', 'danger')
    return render_template('login.html', title='כניסה', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('החשבון שלך עודכן', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename=f'profile_pics/{current_user.image_file}')
    return render_template('account.html', title='חשבון', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('בדקו את המייל שלכם!', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token=token)
    if user is None:
        flash('הקוד לא נכון\לא תקף. בבקשה נסו שוב.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash(
            f'{user.username}, הסיסמה שלך השתנתה! עכשיו אפשר להיכנס!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

flaskblog/templates/posts_templates/post.html.jinja
<article class="media content-section">
    {% block user_spesific_outside_post %}
    {% endblock user_spesific_outside_post %}
    <img class="rounded-circle article-image"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body ml-2">
        <div class="article-metadata">
            {% block user_spesific_inside_post %}
            {% endblock user_spesific_inside_post %}
            <a class="mr-2"
                href="{{ url_for('users.user_posts', username=post.author.username) }}">
                {{ post.author.username }}</a>
            <small class="text-muted">
                {{ post.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        {% if post.link %}
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="{{ post.link }}" allowfullscreen></iframe>
        </div>
        {% endif %}
    </div>
</article>

flaskblog/templates/posts_templates/user_post.html.jinja
{% extends 'posts_templates/post.html.jinja' %}
{% block user_spesific_inside_post %}
    {% if post.author == current_user %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1"
                href="{{ url_for('posts.update_post', post_id=post.id) }}">עדכון</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                data-target="#deleteModal">מחיקה</button>
        </div>
    {% endif %}
{% endblock user_spesific_inside_post %}

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">למחוק פוסט?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">סגירה</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>